volumes:
  mariadb_airbnb:
    #d√©claration du volume pour la base

services:

  # container de bdd
  database:
    #nom de service
    container_name: mariadb_airbnb
    image: mariadb:latest
    ports:
      - '3307:3306'
    volumes:
      - mariadb_airbnb:/var/lib/mysql
      - ./db:/root
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airbnb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  # container php
  php:
    container_name: php_airbnb
    build:
      context: ./php
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '9001:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      TZ: Europe/Paris
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database

  # server web
  nginx:
    container_name: nginx_airbnb
    image: nginx:stable-alpine
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      TZ: Europe/Paris
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - php
      - database
